#+title: Todo list for status
#+AUTHOR: D3faIt

* [0/4] Parser support

We would like to have basic control over checking status, pausing testing, and starting testing.
Detailed control would be desirable.

As the code functions right now, the parser is unable to allow such arguments like this:

#+begin_src bash

$ ./run service check test1 test2 test3
$ ./run service pause test1 test3
$ ./run service start test2 test3

#+end_src

We can't do this because of how the [[https://github.com/clap-rs/clap][clap]] library functions, getting such error:

#+begin_src
error[E0277]: the trait bound `ServiceSubcommand: clap::Args` is not satisfied
  --> src/pipes/listen.rs:21:13
   |
21 |     Service(ServiceSubcommand),
   |             ^^^^^^^^^^^^^^^^^ the trait `clap::Args` is not implemented for `ServiceSubcommand`
   |
   = help: the following other types implement trait `clap::Args`:
             Box<T>
             Cli
             ServiceArgs
#+end_src

** [ ] Baseline

Before we can do Check, Pause, Start, the baseline needs to be done

** HOLD Check

Check should print out the info of the service

** HOLD Pause

Pause should pause checking/testing the service every x seconds

** HOLD Start

Start, pretty much just start it again after having been stopped.

* [ ] Add example command scripts for all 3 formats that actually function like one would use it

To clear up some confusion, this is probably not a bad idea

* [ ] Bash script support error code returns

Right now the bash script only handles exit code 0, 1 and 124. These are success, file not found and timeout.
We want to pass the exit code from the rust application to bash somehow too

* [ ] Add timestamp to printing

Nice to have

* [ ] Some way to easily show failed services
